
platform :ios, '8.0' #手机的系统
use_frameworks!
target 'NicooRouterTestProject' do
 
 # Demo 模拟 在组件B（RouterTestModule）中需要用到组件A（RightMuneTabel）中的信息，通过路由器 （NicooSwiftRouter）去组件A中获取
 
pod 'RouterTestModule' # 组件B
pod 'RightMuneTabel'  # 组件A
pod 'NicooSwiftRouter'    # 路由器组件
end
